spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: Bank
    password: kCS@#123
    url: jdbc:mysql://localhost:3306/Bank
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
      gateway:
        routes:
           - id: ACCOUNT-CREATION-FORM
             uri: lb://ACCOUNT-CREATION-FORM
             predicates:
                  - Path=/bank2/**
           - id: BANK-BALANCE-CHECK-FORM
             uri: lb://BANK-BALANCE-CHECK-FORM
             predicates:
                  - Path=/bank3/**
          - id: BANK-CREATION-FORM
             uri: lb://BANK-CREATION-FORM
             predicates:
                  - Path=/bank/**
          - id: FETCH-CUSTOMER-DETAILS-SERVICE
             uri: lb://FETCH-CUSTOMER-DETAILS-SERVICE
             predicates:
                  - Path=/bank4/**
         - id: TRANSACTION-FORM
             uri: lb://TRANSACTION-FORM
             predicates:
                  - Path=/bank3/**
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/         
